---
- name: Create ansible service account
  hosts: all
  become: true

  tasks:
    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        create_home: true
        state: present

    - name: Add ansible public key
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id.pub') }}"
